staging:
  domain: 'deploy@psychomatix.info'
  deploy_to: '/home/deploy/gds'
  repository: 'git@github.com:tim-friedrich/group-discussion-services.git'
  branch: "staging"
  post_deploy_script: config/post_deploy.sh
  post_setup_script: config/post_deploy.sh
  rake_env:
    RAILS_ENV: 'production'