development:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
  rackup: private_pub.ru
test:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
  rackup: private_pub.ru
production:
  server: "https://group-discussion-services.herokuapp.com/faye"
  secret_token: "559c1806ca482ab39f941d5755cf38d44ce470ad9c0fe6db83dd20ac6262a0cb"
  signature_expiration: 3600 # one hour
  rackup: private_pub.ru
